2025-02-04 17:11:11,085 INFO    MainThread:26132 [wandb_init.py:setup_run_log_directory():637] Logging user logs to c:\Users\costa\Documents\GitHub\Deep_learning_for_medical_imaging\wandb\run-20250204_171111-ct2wlx3j\logs\debug.log
2025-02-04 17:11:11,085 INFO    MainThread:26132 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to c:\Users\costa\Documents\GitHub\Deep_learning_for_medical_imaging\wandb\run-20250204_171111-ct2wlx3j\logs\debug-internal.log
2025-02-04 17:11:11,085 INFO    MainThread:26132 [wandb_init.py:monkeypatch_ipython():589] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000183B1C8E360>
2025-02-04 17:11:11,086 INFO    MainThread:26132 [wandb_init.py:init():756] calling init triggers
2025-02-04 17:11:11,087 INFO    MainThread:26132 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-04 17:11:11,088 INFO    MainThread:26132 [wandb_init.py:init():789] starting backend
2025-02-04 17:11:11,088 INFO    MainThread:26132 [wandb_init.py:init():793] sending inform_init request
2025-02-04 17:11:11,090 INFO    MainThread:26132 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-02-04 17:11:11,091 INFO    MainThread:26132 [wandb_init.py:init():808] backend started and connected
2025-02-04 17:11:11,094 INFO    MainThread:26132 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-02-04 17:11:11,095 INFO    MainThread:26132 [wandb_run.py:_label_probe_notebook():1206] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 3678: character maps to <undefined>
2025-02-04 17:11:11,095 INFO    MainThread:26132 [wandb_init.py:init():901] updated telemetry
2025-02-04 17:11:11,159 INFO    MainThread:26132 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-02-04 17:11:11,487 INFO    MainThread:26132 [wandb_init.py:init():984] starting run threads in backend
2025-02-04 17:11:41,909 INFO    MainThread:26132 [wandb_run.py:_console_start():2385] atexit reg
2025-02-04 17:11:41,909 INFO    MainThread:26132 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2025-02-04 17:11:41,909 INFO    MainThread:26132 [wandb_run.py:_redirect():2300] Wrapping output streams.
2025-02-04 17:11:41,909 INFO    MainThread:26132 [wandb_run.py:_redirect():2325] Redirects installed.
2025-02-04 17:11:41,910 INFO    MainThread:26132 [wandb_init.py:init():1026] run started, returning control to user process
2025-02-04 17:11:41,912 INFO    MainThread:26132 [wandb_run.py:_config_callback():1253] config_cb ('_wandb', 'visualize', 'data_plot 0') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/scatter/v0', 'fieldSettings': {'x': 'b-values', 'y': 'signal'}, 'stringSettings': {'title': ''}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'data_plot 0_table'}], 'fields': []}]}]}}} None
2025-02-04 17:11:42,143 INFO    MainThread:26132 [wandb_run.py:_config_callback():1253] config_cb ('_wandb', 'visualize', 'data_plot 1') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/scatter/v0', 'fieldSettings': {'x': 'b-values', 'y': 'signal'}, 'stringSettings': {'title': ''}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'data_plot 1_table'}], 'fields': []}]}]}}} None
2025-02-04 17:11:42,322 INFO    MainThread:26132 [wandb_run.py:_config_callback():1253] config_cb ('_wandb', 'visualize', 'data_plot 2') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/scatter/v0', 'fieldSettings': {'x': 'b-values', 'y': 'signal'}, 'stringSettings': {'title': ''}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'data_plot 2_table'}], 'fields': []}]}]}}} None
2025-02-04 17:11:42,513 INFO    MainThread:26132 [wandb_run.py:_config_callback():1253] config_cb ('_wandb', 'visualize', 'data_plot 3') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/scatter/v0', 'fieldSettings': {'x': 'b-values', 'y': 'signal'}, 'stringSettings': {'title': ''}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'data_plot 3_table'}], 'fields': []}]}]}}} None
2025-02-04 17:11:42,683 INFO    MainThread:26132 [wandb_run.py:_finish():2110] finishing run costanza-dercole-vrije-universiteit-amsterdam/AI_for_medical_imaging/ct2wlx3j
2025-02-04 17:11:42,684 ERROR   MainThread:26132 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-02-04 17:11:42,684 INFO    MainThread:26132 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-02-04 17:11:42,684 INFO    MainThread:26132 [wandb_init.py:_jupyter_teardown():571] cleaning up jupyter logic
2025-02-04 17:11:42,684 INFO    MainThread:26132 [wandb_run.py:_atexit_cleanup():2350] got exitcode: 0
2025-02-04 17:11:42,684 INFO    MainThread:26132 [wandb_run.py:_restore():2332] restore
2025-02-04 17:11:42,685 INFO    MainThread:26132 [wandb_run.py:_restore():2338] restore done
2025-02-04 17:11:43,854 WARNING MsgRouterThr:26132 [router.py:_handle_msg_rcv():111] No listener found for msg with uuid 9deec9fd532447abb98fe6ae1bfcd11b (control {
  req_resp: true
  local: true
  connection_id: "127.0.0.1:64070"
}
uuid: "9deec9fd532447abb98fe6ae1bfcd11b"
response {
  log_artifact_response {
    artifact_id: "QXJ0aWZhY3Q6MTQ4ODk0NjgyOA=="
  }
}
)
2025-02-04 17:11:44,193 WARNING MsgRouterThr:26132 [router.py:_handle_msg_rcv():111] No listener found for msg with uuid 36240d572d164991bc3dc86c12fe4832 (control {
  req_resp: true
  local: true
  connection_id: "127.0.0.1:64070"
}
uuid: "36240d572d164991bc3dc86c12fe4832"
response {
  log_artifact_response {
    artifact_id: "QXJ0aWZhY3Q6MTQ4ODk0NjgzNw=="
  }
}
)
2025-02-04 17:12:50,509 INFO    MainThread:26132 [wandb_init.py:setup_run_log_directory():637] Logging user logs to c:\Users\costa\Documents\GitHub\Deep_learning_for_medical_imaging\wandb\run-20250204_171250-1joh94mh\logs\debug.log
2025-02-04 17:12:50,509 INFO    MainThread:26132 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to c:\Users\costa\Documents\GitHub\Deep_learning_for_medical_imaging\wandb\run-20250204_171250-1joh94mh\logs\debug-internal.log
2025-02-04 17:12:50,509 INFO    MainThread:26132 [wandb_init.py:monkeypatch_ipython():589] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000183B227C8C0>
2025-02-04 17:12:50,511 INFO    MainThread:26132 [wandb_init.py:init():756] calling init triggers
2025-02-04 17:12:50,512 INFO    MainThread:26132 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-04 17:12:50,512 INFO    MainThread:26132 [wandb_init.py:init():789] starting backend
2025-02-04 17:12:50,512 INFO    MainThread:26132 [wandb_init.py:init():793] sending inform_init request
2025-02-04 17:12:50,514 INFO    MainThread:26132 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-02-04 17:12:50,515 INFO    MainThread:26132 [wandb_init.py:init():808] backend started and connected
2025-02-04 17:12:50,517 INFO    MainThread:26132 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-02-04 17:12:50,517 INFO    MainThread:26132 [wandb_run.py:_label_probe_notebook():1206] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 3678: character maps to <undefined>
2025-02-04 17:12:50,517 INFO    MainThread:26132 [wandb_init.py:init():901] updated telemetry
2025-02-04 17:12:50,559 INFO    MainThread:26132 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-02-04 17:13:51,064 WARNING MainThread:26132 [wandb_init.py:init():1465] interrupted
Traceback (most recent call last):
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 931, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-02-04 17:14:32,470 INFO    MainThread:26132 [wandb_init.py:setup_run_log_directory():637] Logging user logs to c:\Users\costa\Documents\GitHub\Deep_learning_for_medical_imaging\wandb\run-20250204_171432-1ttjnguf\logs\debug.log
2025-02-04 17:14:32,471 INFO    MainThread:26132 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to c:\Users\costa\Documents\GitHub\Deep_learning_for_medical_imaging\wandb\run-20250204_171432-1ttjnguf\logs\debug-internal.log
2025-02-04 17:14:32,471 INFO    MainThread:26132 [wandb_init.py:init():756] calling init triggers
2025-02-04 17:14:32,471 INFO    MainThread:26132 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-04 17:14:32,472 INFO    MainThread:26132 [wandb_init.py:init():789] starting backend
2025-02-04 17:14:32,475 INFO    MainThread:26132 [wandb_init.py:init():793] sending inform_init request
2025-02-04 17:14:32,477 INFO    MainThread:26132 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-02-04 17:14:32,477 INFO    MainThread:26132 [wandb_init.py:init():808] backend started and connected
2025-02-04 17:14:32,479 INFO    MainThread:26132 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-02-04 17:14:32,480 INFO    MainThread:26132 [wandb_run.py:_label_probe_notebook():1206] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 3678: character maps to <undefined>
2025-02-04 17:14:32,480 INFO    MainThread:26132 [wandb_init.py:init():901] updated telemetry
2025-02-04 17:14:32,515 INFO    MainThread:26132 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-02-04 17:16:03,179 ERROR   MainThread:26132 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 950, in init
    raise CommError(
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-02-04 17:16:50,867 INFO    MainThread:26132 [wandb_init.py:setup_run_log_directory():637] Logging user logs to c:\Users\costa\Documents\GitHub\Deep_learning_for_medical_imaging\wandb\run-20250204_171650-dxyr68mo\logs\debug.log
2025-02-04 17:16:50,867 INFO    MainThread:26132 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to c:\Users\costa\Documents\GitHub\Deep_learning_for_medical_imaging\wandb\run-20250204_171650-dxyr68mo\logs\debug-internal.log
2025-02-04 17:16:50,867 INFO    MainThread:26132 [wandb_init.py:init():756] calling init triggers
2025-02-04 17:16:50,867 INFO    MainThread:26132 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-04 17:16:50,867 INFO    MainThread:26132 [wandb_init.py:init():789] starting backend
2025-02-04 17:16:50,868 INFO    MainThread:26132 [wandb_init.py:init():793] sending inform_init request
2025-02-04 17:16:50,869 INFO    MainThread:26132 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-02-04 17:16:50,870 INFO    MainThread:26132 [wandb_init.py:init():808] backend started and connected
2025-02-04 17:16:50,872 INFO    MainThread:26132 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-02-04 17:16:50,873 INFO    MainThread:26132 [wandb_run.py:_label_probe_notebook():1206] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 3678: character maps to <undefined>
2025-02-04 17:16:50,873 INFO    MainThread:26132 [wandb_init.py:init():901] updated telemetry
2025-02-04 17:16:50,918 INFO    MainThread:26132 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-02-04 17:16:51,283 INFO    MainThread:26132 [wandb_init.py:init():984] starting run threads in backend
2025-02-04 17:17:21,568 WARNING MainThread:26132 [wandb_init.py:init():1465] interrupted
Traceback (most recent call last):
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 998, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\costa\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
